### ISSUE TITLE
Issue/Enhancement:  ConvertTo-TWS.ps1 Script Removes Symbols With Earnings Days Under 0

### ISSUE THREAD

**Issue by SCCMAdmin** [wahidsaleemi/finance#5]
As suggested in Issue #4 : 

Current ConvertTo-TWS.ps1 script output for a stock that has earnings today or just passed (yesterday is -1) looks like:
_RPM has earnings less than 14 days, in -2. Removing from list._

Note RPM above. Shows earnings less than 14 days because the number -2 (or 0 too) is under 14. A negative number means the earnings have already past. -2 means 2 days ago. This stock does not need to be removed from the list. Better still, this is a stock where HV would be falling after a earnings based peak. Actually could be a great time for a spread (sell high buy low).

Please code around this scenario. 
1. Output suggestion might be:
_RPM had earnings -2 days ago, HV could be falling from elevated levels_
2. Don't remove this symbol from the list. The "-2" is the value/variable. Using Volatility Lab in TWS does actually show RPM with elevated HV coming down off the earnings peak show a cooling per theory as educated in course.

The scenario may not be long lived. I've already manually rechecked RPM at https://www.earningswhispers.com/stocks/rpm and it already has the new future date now, so the script result won't be -2 any longer. If you need another stock example let me know.

Thank you Sir!

**Comment by SCCMAdmin** [comment]
See pull request #7 to assist in closing this issue out whilst performing a mini overhaul of sorts. Thanks @wahidsaleemi

**Comment by wahidsaleemi** [comment]
This has been fixed in the latest version. Thanks @SCCMAdmin
